# Generated by Django 2.2.7 on 2019-11-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191120_1704'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PizzaSubs',
        ),
        migrations.DeleteModel(
            name='Toppings',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
