# Generated by Django 2.2.7 on 2019-11-20 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_pizzasubs_toppings_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzasubs',
            name='type',
        ),
    ]
