# Generated by Django 2.2.7 on 2019-11-21 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20191120_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('L', 'Large'), ('S', 'Small')], default='S', max_length=15)),
                ('base', models.CharField(choices=[('none', 'none'), ('ch', 'cheese'), ('1', '1 topping'), ('2', '2 toppings'), ('3', '3 toppings'), ('spec', 'special')], default='none', max_length=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('toppings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Toppings')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Type')),
            ],
        ),
    ]
