# Generated by Django 2.2.7 on 2019-11-26 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=None, max_length=65)),
                ('topping', models.CharField(default=None, max_length=65)),
                ('quantity', models.IntegerField(default=None)),
                ('user', models.CharField(default=None, max_length=65)),
                ('price', models.DecimalField(decimal_places=2, default='0.00', max_digits=5)),
                ('is_ordered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
                ('price', models.DecimalField(decimal_places=2, default='0.00', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('base', models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='orders.Base')),
                ('category', models.ForeignKey(default='regular pizza', on_delete=django.db.models.deletion.CASCADE, to='orders.Category')),
                ('size', models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='orders.Size')),
            ],
        ),
    ]
