# Generated by Django 2.2.7 on 2019-11-26 21:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 11, 26, 21, 39, 30, 942445, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='topping2',
            field=models.CharField(default=0, max_length=65),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='topping3',
            field=models.CharField(default=0, max_length=65),
            preserve_default=False,
        ),
    ]
