# Generated by Django 2.2.7 on 2019-11-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191126_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='topping2',
            field=models.CharField(default='None', max_length=65),
        ),
        migrations.AlterField(
            model_name='order',
            name='topping3',
            field=models.CharField(default='None', max_length=65),
        ),
    ]
