# Generated by Django 2.2.7 on 2019-11-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191126_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='topping',
            field=models.CharField(default='None', max_length=65),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(default='None', max_length=65),
        ),
    ]
