# Generated by Django 2.2.7 on 2019-11-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='None', max_length=65)),
                ('topping', models.CharField(default='None', max_length=65)),
                ('topping2', models.CharField(default='None', max_length=65)),
                ('topping3', models.CharField(default='None', max_length=65)),
                ('quantity', models.IntegerField(default='0')),
                ('user', models.CharField(default='None', max_length=65)),
                ('price', models.DecimalField(decimal_places=2, default='0.00', max_digits=5)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('is_ordered', models.BooleanField(default=False)),
            ],
        ),
    ]
