# Generated by Django 2.2.7 on 2019-11-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='topping',
            field=models.CharField(blank=True, max_length=65),
        ),
        migrations.AlterField(
            model_name='order',
            name='topping2',
            field=models.CharField(blank=True, max_length=65),
        ),
        migrations.AlterField(
            model_name='order',
            name='topping3',
            field=models.CharField(blank=True, max_length=65),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(blank=True, max_length=65),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.CharField(blank=True, max_length=65),
        ),
    ]
