# Generated by Django 2.2.7 on 2019-11-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20191127_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_added',
            field=models.BooleanField(default=False),
        ),
    ]
